<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "participants"
 *
 * Auto generated by Extension Builder 2020-03-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Download library',
    'description' => 'Mittels dieser Erweiterung können FE-User Downloads zur Verfügung stellen.
Change log:
0.0.13 :: BUG: fixing the caching
0.0.12 :: BUG: fix the redirect after upload.
0.0.9 :: First beta',
    'category' => 'plugin',
    'author' => 'C. Gogolin',
    'author_email' => 'service@cylancer.net',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '0.0.13',
    'constraints' => [
        'depends' => [
            'typo3' => '11.5.00-11.5.99',
            'bootstrap_package' => '11.0.2-12.9.99'
            
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
