<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "download_library"
 *
 * Auto generated by Extension Builder 2020-03-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Download library',
    'description' => 'By means of this extension FE users can provide downloads.',
    'category' => 'plugin',
    'author' => 'C. Gogolin',
    'author_email' => 'service@cylancer.net',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '2.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '12.4.00-12.4.99',
            'bootstrap_package' => '13.0.2-13.9.99'
            
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];


/** CHANGE-LOG
 * 2.0.0   UPD  :: to TYPO3 12.4.x
 * 1.0.1   FIX  :: Remove button is visible for document owner. 
 * 1.0.0   FIX  :: Fix the plugin configuration/registry.
 * 0.1.1   BUG  :: Remove debug outout. 
 * 0.1.0   BUG  :: The document remove button is display only for the document owner. 
 * 0.0.13  BUG  :: fixing the caching
 * 0.0.12  BUG  :: fix the redirect after upload.
 * 0.0.9   INIT :: First beta',
 */